### ISSUE TITLE
Can I use my own dataset?

### ISSUE THREAD

**Issue by ziFan99** [HanzhouLiu/DeblurDiNAT#10]
Not the motion-blurred GoPro dataset, but a DPDD-like dataset with defocus blur.

**Comment by HanzhouLiu** [comment]
Yes, as far as I know, motion deblur and defocus deblur datasets have very
similar structures. However, my model is not designed for Defocus deblur.
So you may need to tune the network so that it performs well on the new
task. Thank you.

**Comment by akshu281** [comment]
Hello author, how do you recommend using the network for other kinds of blur like local deblur? @HanzhouLiu

**Comment by HanzhouLiu** [comment]
If you would like to apply DeblurDiNAT to images with only local blur. You
are expected to get rid of all global blocks.

Thank you.
