### ISSUE TITLE
LCCL

### ISSUE THREAD

**Issue by zhangxin-516** [HanzhouLiu/DeblurDiNAT#12]
![图片](https://github.com/user-attachments/assets/753c44bd-83e9-4987-843f-677930c4cb62)
图片中的是LCCL模块的内容，为什么卷积核是3啊，文献中说的不是1吗

**Comment by HanzhouLiu** [comment]
您好，文中说的是1D
conv，指的是对于1D序列进行卷积，可以使用任意大小的卷积核，我们目前只使用了k=3，您可以调试这个参数，尝试更大的range。它改变的会是在1D序列上的感受野。
