### ISSUE TITLE
there is no train_DeblurDiNAT_gopro.py

### ISSUE THREAD

**Issue by xuyuan-qd** [HanzhouLiu/DeblurDiNAT#2]
could you please upload this file?

**Comment by HanzhouLiu** [comment]
Sure. I would upload the results and training file asap.

**Comment by nonick2k23** [comment]
Hello,

It's been over a month. Will you upload it ?

Thanks.

**Comment by smsver2** [comment]
I have the same problem.

**Comment by HanzhouLiu** [comment]
> Hello,
> 
> It's been over a month. Will you upload it ?
> 
> Thanks.

I updated the paper, which should be visible the next week. New model weights and codes have been uploaded.

**Comment by HanzhouLiu** [comment]
> I have the same problem.

I updated the paper, which should be visible the next week. New model weights and codes have been uploaded.

**Comment by nonick2k23** [comment]
Thank you @HanzhouLiu ! very appreciated.

Edit: 
`
......................DeblurDiNAT/models/losses.py", line 5, in <module> 
from models.torch_wavelets import DWT_2D
ModuleNotFoundError: No module named 'models.torch_wavelets'
`

Any input regarding this error? Which package contains DWT_2D? 

Edit 2:
can you fix https://drive.google.com/drive/folders/1BdV2l7A5MRXLWszGonMxR88eV27geb_n?usp=sharing
there is no GoPro dataset there (404 error)

Also GoPro from official website does not have trainA and trainB folders as stated in your YAML files - can you explain how did you generate them?

Thanks

**Comment by HanzhouLiu** [comment]
> Thank you @HanzhouLiu ! very appreciated.
> 
> Edit: `......................DeblurDiNAT/models/losses.py", line 5, in <module> from models.torch_wavelets import DWT_2D ModuleNotFoundError: No module named 'models.torch_wavelets'`
> 
> Any input regarding this error? Which package contains DWT_2D?
> 
> Edit 2: can you fix https://drive.google.com/drive/folders/1BdV2l7A5MRXLWszGonMxR88eV27geb_n?usp=sharing there is no GoPro dataset there (404 error)
> 
> Also GoPro from official website does not have trainA and trainB folders as stated in your YAML files - can you explain how did you generate them?
> 
> Thanks

Thanks for letting me know. I already removed those lines of codes in the latest version, or you can just comment them out. trainA is just the blur. I am still uploading the gopro dataset, which should be available at 13:00 06/28 CST.

**Comment by nonick2k23** [comment]
Thanks for the update.

One more issue:

Your dataset code contains sub-folders inside trainA/trainB folders, however your data loader does *not* account for these sub-folders and expects all the files to be under trianA/trainB without being separated to sub-folders (GOPR0372_07_00/GOPR0372_07_01/etc...)

This way the loader code or the dataset structure needs to be fixed in order for training code to run properly.

Which way do you suggest? 

Thanks

**Comment by HanzhouLiu** [comment]
> Thanks for the update.
> 
> One more issue:
> 
> Your dataset code contains sub-folders inside trainA/trainB folders, however your data loader does _not_ account for these sub-folders and expects all the files to be under trianA/trainB without being separated to sub-folders (GOPR0372_07_00/GOPR0372_07_01/etc...)
> 
> This way the loader code or the dataset structure needs to be fixed in order for training code to run properly.
> 
> Which way do you suggest?
> 
> Thanks

The dataset codes does not affect training codes. We only have two subsets of images, blurred and sharp. If your dataset does not contain sub-folders, you just need to remove one of the for loops.
