### ISSUE TITLE
Unexpected key(s) in state_dict

### ISSUE THREAD

**Issue by Ramesik** [HanzhouLiu/DeblurDiNAT#4]
I used pretrained DeblurDiNATL.pth downloaded from link in ReadME
I tried to run script on the mac and change line 34 to use cpu > ck = torch.load(weights_path, map_location=torch.device('cpu'))

predict_GoPro_test_results.py --weight_name=DeblurDiNATL.pth --blur_path=./inputData/DeblurDiNAT
Traceback (most recent call last):
  File "predict_GoPro_test_results.py", line 38, in <module>
    model.load_state_dict(ck)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Unexpected key(s) in state_dict: "module.decoder.de_trans_level3.0.na2d.rpb", "module.decoder.de_trans_level3.1.na2d.rpb", "module.decoder.de_trans_level3.2.na2d.rpb", "module.decoder.de_trans_level3.3.na2d.rpb", "module.decoder.de_trans_level3.4.na2d.rpb", "module.decoder.de_trans_level3.5.na2d.rpb", "module.decoder.de_trans_level3.6.na2d.rpb", "module.decoder.de_trans_level3.7.na2d.rpb", "module.decoder.de_trans_level3.8.na2d.rpb", "module.decoder.de_trans_level3.9.na2d.rpb", "module.decoder.de_trans_level3.10.na2d.rpb", "module.decoder.de_trans_level3.11.na2d.rpb", "module.decoder.de_trans_level3.12.na2d.rpb", "module.decoder.de_trans_level3.13.na2d.rpb", "module.decoder.de_trans_level3.14.na2d.rpb", "module.decoder.de_trans_level3.15.na2d.rpb", "module.decoder.de_trans_level3.16.na2d.rpb", "module.decoder.de_trans_level3.17.na2d.rpb", "module.decoder.de_trans_level2.0.na2d.rpb", "module.decoder.de_trans_level2.1.na2d.rpb", "module.decoder.de_trans_level2.2.na2d.rpb", "module.decoder.de_trans_level2.3.na2d.rpb", "module.decoder.de_trans_level2.4.na2d.rpb", "module.decoder.de_trans_level2.5.na2d.rpb", "module.decoder.de_trans_level2.6.na2d.rpb", "module.decoder.de_trans_level2.7.na2d.rpb", "module.decoder.de_trans_level2.8.na2d.rpb", "module.decoder.de_trans_level2.9.na2d.rpb", "module.decoder.de_trans_level2.10.na2d.rpb", "module.decoder.de_trans_level2.11.na2d.rpb", "module.decoder.de_trans_level1.0.na2d.rpb", "module.decoder.de_trans_level1.1.na2d.rpb", "module.decoder.de_trans_level1.2.na2d.rpb", "module.decoder.de_trans_level1.3.na2d.rpb", "module.decoder.de_trans_level1.4.na2d.rpb", "module.decoder.de_trans_level1.5.na2d.rpb", "module.decoder.refinement.0.na2d.rpb", "module.decoder.refinement.1.na2d.rpb", "module.decoder.refinement.2.na2d.rpb", "module.decoder.refinement.3.na2d.rpb", "module.decoder.refinement.4.na2d.rpb", "module.decoder.refinement.5.na2d.rpb".

**Comment by HanzhouLiu** [comment]
I have not test it on a Mac yet. I did the test on a 3090 GPU and had no issue. I guess it is a cuda/DataParallel issue. I suggest you run it on a GPU rather than a CPU. Thank you!

**Comment by Ramesik** [comment]
I tried on GPU, install all components with cuda support, but get same error.
Seems that .pth file is wrong or maybe not last code version in the repository?

**Comment by Ramesik** [comment]
If I use python 3.8 conda environment I got another error

```
Traceback (most recent call last):
  File "predict_GoPro_test_results.py", line 8, in <module>
    from models.networks import get_generator
  File "/workspace/DeblurDiNAT/models/networks.py", line 3, in <module>
    from models.DeblurDiNATL import NADeblurL
  File "/workspace/DeblurDiNAT/models/DeblurDiNATL.py", line 7, in <module>
    from natten import NeighborhoodAttention1D, NeighborhoodAttention2D
  File "/opt/conda/envs/DeblurDiNAT/lib/python3.8/site-packages/natten/__init__.py", line 24, in <module>
    from .context import (
  File "/opt/conda/envs/DeblurDiNAT/lib/python3.8/site-packages/natten/context.py", line 29, in <module>
    from .utils import log
  File "/opt/conda/envs/DeblurDiNAT/lib/python3.8/site-packages/natten/utils/__init__.py", line 24, in <module>
    from .checks import (
  File "/opt/conda/envs/DeblurDiNAT/lib/python3.8/site-packages/natten/utils/checks.py", line 27, in <module>
    from ..types import (
  File "/opt/conda/envs/DeblurDiNAT/lib/python3.8/site-packages/natten/types.py", line 36, in <module>
    DimensionType = Dimension1DType | Dimension2DType | Dimension3DType
TypeError: unsupported operand type(s) for |: '_GenericAlias' and '_GenericAlias'
```

**Comment by HanzhouLiu** [comment]
Sorry, I never met such an issue. I am not sure what is the root cause of that. It might be that natten was not installed correctly.

**Comment by akshu281** [comment]
@Ramesik - were you able to solve this Unexpected key(s) in state_dict: "module.decoder.de_trans_level3.0.na2d.rpb", "module.decoder.de_trans_level3.1.na2d.rpb" issue? But I do not use Mac!

I encounter the same despite installing natten as per the requirements -@HanzhouLiu - any thoughts?
![image](https://github.com/user-attachments/assets/659114f7-8689-44fe-a585-9fa381b043fe)

**Comment by HanzhouLiu** [comment]
> @Ramesik - were you able to solve this Unexpected key(s) in state_dict: "module.decoder.de_trans_level3.0.na2d.rpb", "module.decoder.de_trans_level3.1.na2d.rpb" issue? But I do not use Mac!
> 
> I encounter the same despite installing natten as per the requirements -@HanzhouLiu - any thoughts? ![image](https://private-user-images.githubusercontent.com/35450160/384244175-659114f7-8689-44fe-a585-9fa381b043fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNDcxNjEsIm5iZiI6MTczMTA0Njg2MSwicGF0aCI6Ii8zNTQ1MDE2MC8zODQyNDQxNzUtNjU5MTE0ZjctODY4OS00NGZlLWE1ODUtOWZhMzgxYjA0M2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA2MjEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMzljMzhjMjZkNmRmMmFmY2NiODI1ZTc1NDNmYWJlM2VjOTc1ZWUwNzk5ZDY4NGI4ZGNlNmU5YmU0M2FhMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R5MNdyMS3HLdMXBOR-AmX2n7eIT9UOoQPzcSquXCv1o)

Very weird. All Natten layers' weights were not loaded correctly in your log. I haven't meet such an issue. Could you post the whole error message? My first idea is that the installation of Natten is incorrect. Anyway, I would double check my codes and environment settings later (way too busy recently, sry for that). I used StripFormer as the codebase. You can also check issues in Natten GitHub repository.

**Comment by akshu281** [comment]
Here's the complete traceback for your reference -- I am using torch 2.3.0 and cuda 118 on virutalenv with py3.8

Traceback (most recent call last):
  File "predict_GoPro_test_results.py", line 48, in <module>
    model.load_state_dict(ck)
  File "/home/user/Documents/A/DeblurDiNAT/natten_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Unexpected key(s) in state_dict: "module.decoder.de_trans_level3.0.na2d.rpb", "module.decoder.de_trans_level3.1.na2d.rpb", "module.decoder.de_trans_level3.2.na2d.rpb", "module.decoder.de_trans_level3.3.na2d.rpb", "module.decoder.de_trans_level3.4.na2d.rpb", "module.decoder.de_trans_level3.5.na2d.rpb", "module.decoder.de_trans_level3.6.na2d.rpb", "module.decoder.de_trans_level3.7.na2d.rpb", "module.decoder.de_trans_level3.8.na2d.rpb", "module.decoder.de_trans_level3.9.na2d.rpb", "module.decoder.de_trans_level3.10.na2d.rpb", "module.decoder.de_trans_level3.11.na2d.rpb", "module.decoder.de_trans_level3.12.na2d.rpb", "module.decoder.de_trans_level3.13.na2d.rpb", "module.decoder.de_trans_level3.14.na2d.rpb", "module.decoder.de_trans_level3.15.na2d.rpb", "module.decoder.de_trans_level3.16.na2d.rpb", "module.decoder.de_trans_level3.17.na2d.rpb", "module.decoder.de_trans_level2.0.na2d.rpb", "module.decoder.de_trans_level2.1.na2d.rpb", "module.decoder.de_trans_level2.2.na2d.rpb", "module.decoder.de_trans_level2.3.na2d.rpb", "module.decoder.de_trans_level2.4.na2d.rpb", "module.decoder.de_trans_level2.5.na2d.rpb", "module.decoder.de_trans_level2.6.na2d.rpb", "module.decoder.de_trans_level2.7.na2d.rpb", "module.decoder.de_trans_level2.8.na2d.rpb", "module.decoder.de_trans_level2.9.na2d.rpb", "module.decoder.de_trans_level2.10.na2d.rpb", "module.decoder.de_trans_level2.11.na2d.rpb", "module.decoder.de_trans_level1.0.na2d.rpb", "module.decoder.de_trans_level1.1.na2d.rpb", "module.decoder.de_trans_level1.2.na2d.rpb", "module.decoder.de_trans_level1.3.na2d.rpb", "module.decoder.de_trans_level1.4.na2d.rpb", "module.decoder.de_trans_level1.5.na2d.rpb", "module.decoder.refinement.0.na2d.rpb", "module.decoder.refinement.1.na2d.rpb", "module.decoder.refinement.2.na2d.rpb", "module.decoder.refinement.3.na2d.rpb", "module.decoder.refinement.4.na2d.rpb", "module.decoder.refinement.5.na2d.rpb". 
	
Yes indeed all the rpb's are not loading as is -- only works when the strictness is negated for the inference to work during state dict load, but I believe it will affect the performance isn't it?

**Comment by akshu281** [comment]
> Here's the complete traceback for your reference -- I am using torch 2.3.0 and cuda 118 on virutalenv with py3.8
> 
> Traceback (most recent call last): File "predict_GoPro_test_results.py", line 48, in model.load_state_dict(ck) File "/home/user/Documents/A/DeblurDiNAT/natten_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for DataParallel: Unexpected key(s) in state_dict: "module.decoder.de_trans_level3.0.na2d.rpb", "module.decoder.de_trans_level3.1.na2d.rpb", "module.decoder.de_trans_level3.2.na2d.rpb", "module.decoder.de_trans_level3.3.na2d.rpb", "module.decoder.de_trans_level3.4.na2d.rpb", "module.decoder.de_trans_level3.5.na2d.rpb", "module.decoder.de_trans_level3.6.na2d.rpb", "module.decoder.de_trans_level3.7.na2d.rpb", "module.decoder.de_trans_level3.8.na2d.rpb", "module.decoder.de_trans_level3.9.na2d.rpb", "module.decoder.de_trans_level3.10.na2d.rpb", "module.decoder.de_trans_level3.11.na2d.rpb", "module.decoder.de_trans_level3.12.na2d.rpb", "module.decoder.de_trans_level3.13.na2d.rpb", "module.decoder.de_trans_level3.14.na2d.rpb", "module.decoder.de_trans_level3.15.na2d.rpb", "module.decoder.de_trans_level3.16.na2d.rpb", "module.decoder.de_trans_level3.17.na2d.rpb", "module.decoder.de_trans_level2.0.na2d.rpb", "module.decoder.de_trans_level2.1.na2d.rpb", "module.decoder.de_trans_level2.2.na2d.rpb", "module.decoder.de_trans_level2.3.na2d.rpb", "module.decoder.de_trans_level2.4.na2d.rpb", "module.decoder.de_trans_level2.5.na2d.rpb", "module.decoder.de_trans_level2.6.na2d.rpb", "module.decoder.de_trans_level2.7.na2d.rpb", "module.decoder.de_trans_level2.8.na2d.rpb", "module.decoder.de_trans_level2.9.na2d.rpb", "module.decoder.de_trans_level2.10.na2d.rpb", "module.decoder.de_trans_level2.11.na2d.rpb", "module.decoder.de_trans_level1.0.na2d.rpb", "module.decoder.de_trans_level1.1.na2d.rpb", "module.decoder.de_trans_level1.2.na2d.rpb", "module.decoder.de_trans_level1.3.na2d.rpb", "module.decoder.de_trans_level1.4.na2d.rpb", "module.decoder.de_trans_level1.5.na2d.rpb", "module.decoder.refinement.0.na2d.rpb", "module.decoder.refinement.1.na2d.rpb", "module.decoder.refinement.2.na2d.rpb", "module.decoder.refinement.3.na2d.rpb", "module.decoder.refinement.4.na2d.rpb", "module.decoder.refinement.5.na2d.rpb".
> 
> Yes indeed all the rpb's are not loading as is -- only works when the strictness is negated for the inference to work during state dict load, but I believe it will affect the performance isn't it?

![image](https://github.com/user-attachments/assets/0cbf5c40-9d43-4a40-845f-747efc95e6f0)


My natten test sample worked as expected I guess -- assuming the package installation is correct?

**Comment by HanzhouLiu** [comment]
> > Here's the complete traceback for your reference -- I am using torch 2.3.0 and cuda 118 on virutalenv with py3.8
> > Traceback (most recent call last): File "predict_GoPro_test_results.py", line 48, in model.load_state_dict(ck) File "/home/user/Documents/A/DeblurDiNAT/natten_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for DataParallel: Unexpected key(s) in state_dict: "module.decoder.de_trans_level3.0.na2d.rpb", "module.decoder.de_trans_level3.1.na2d.rpb", "module.decoder.de_trans_level3.2.na2d.rpb", "module.decoder.de_trans_level3.3.na2d.rpb", "module.decoder.de_trans_level3.4.na2d.rpb", "module.decoder.de_trans_level3.5.na2d.rpb", "module.decoder.de_trans_level3.6.na2d.rpb", "module.decoder.de_trans_level3.7.na2d.rpb", "module.decoder.de_trans_level3.8.na2d.rpb", "module.decoder.de_trans_level3.9.na2d.rpb", "module.decoder.de_trans_level3.10.na2d.rpb", "module.decoder.de_trans_level3.11.na2d.rpb", "module.decoder.de_trans_level3.12.na2d.rpb", "module.decoder.de_trans_level3.13.na2d.rpb", "module.decoder.de_trans_level3.14.na2d.rpb", "module.decoder.de_trans_level3.15.na2d.rpb", "module.decoder.de_trans_level3.16.na2d.rpb", "module.decoder.de_trans_level3.17.na2d.rpb", "module.decoder.de_trans_level2.0.na2d.rpb", "module.decoder.de_trans_level2.1.na2d.rpb", "module.decoder.de_trans_level2.2.na2d.rpb", "module.decoder.de_trans_level2.3.na2d.rpb", "module.decoder.de_trans_level2.4.na2d.rpb", "module.decoder.de_trans_level2.5.na2d.rpb", "module.decoder.de_trans_level2.6.na2d.rpb", "module.decoder.de_trans_level2.7.na2d.rpb", "module.decoder.de_trans_level2.8.na2d.rpb", "module.decoder.de_trans_level2.9.na2d.rpb", "module.decoder.de_trans_level2.10.na2d.rpb", "module.decoder.de_trans_level2.11.na2d.rpb", "module.decoder.de_trans_level1.0.na2d.rpb", "module.decoder.de_trans_level1.1.na2d.rpb", "module.decoder.de_trans_level1.2.na2d.rpb", "module.decoder.de_trans_level1.3.na2d.rpb", "module.decoder.de_trans_level1.4.na2d.rpb", "module.decoder.de_trans_level1.5.na2d.rpb", "module.decoder.refinement.0.na2d.rpb", "module.decoder.refinement.1.na2d.rpb", "module.decoder.refinement.2.na2d.rpb", "module.decoder.refinement.3.na2d.rpb", "module.decoder.refinement.4.na2d.rpb", "module.decoder.refinement.5.na2d.rpb".
> > Yes indeed all the rpb's are not loading as is -- only works when the strictness is negated for the inference to work during state dict load, but I believe it will affect the performance isn't it?
> 
> ![image](https://private-user-images.githubusercontent.com/35450160/384255868-0cbf5c40-9d43-4a40-845f-747efc95e6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjYwOTUsIm5iZiI6MTczMTQ2NTc5NSwicGF0aCI6Ii8zNTQ1MDE2MC8zODQyNTU4NjgtMGNiZjVjNDAtOWQ0My00YTQwLTg0NWYtNzQ3ZWZjOTVlNmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAyNDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NTk4NDU5YzkxZDNmMWM1N2Q0MTIwNmFiNzFlMmJlNjY4OWI0OGYwZjUzZTkyZjk3N2UzNTE4YmU4YzY5ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pQUUzhf1eUOeBdixIb-kka5NzYvkApG_sflUqeovjBE)
> 
> My natten test sample worked as expected I guess -- assuming the package installation is correct?

Thank you for your patience, and apologies for the delayed response. Your information is very helpful to me. I’ve been busy with other tasks but have started looking into this issue. I noticed the same issue on my local 3090 GPU, whereas the test code runs smoothly on my remote cluster. I’m currently comparing the latest code version on the cluster with the older one on my local setup. I’ll update you as soon as I make progress.

**Comment by HanzhouLiu** [comment]
> > Here's the complete traceback for your reference -- I am using torch 2.3.0 and cuda 118 on virutalenv with py3.8
> > Traceback (most recent call last): File "predict_GoPro_test_results.py", line 48, in model.load_state_dict(ck) File "/home/user/Documents/A/DeblurDiNAT/natten_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for DataParallel: Unexpected key(s) in state_dict: "module.decoder.de_trans_level3.0.na2d.rpb", "module.decoder.de_trans_level3.1.na2d.rpb", "module.decoder.de_trans_level3.2.na2d.rpb", "module.decoder.de_trans_level3.3.na2d.rpb", "module.decoder.de_trans_level3.4.na2d.rpb", "module.decoder.de_trans_level3.5.na2d.rpb", "module.decoder.de_trans_level3.6.na2d.rpb", "module.decoder.de_trans_level3.7.na2d.rpb", "module.decoder.de_trans_level3.8.na2d.rpb", "module.decoder.de_trans_level3.9.na2d.rpb", "module.decoder.de_trans_level3.10.na2d.rpb", "module.decoder.de_trans_level3.11.na2d.rpb", "module.decoder.de_trans_level3.12.na2d.rpb", "module.decoder.de_trans_level3.13.na2d.rpb", "module.decoder.de_trans_level3.14.na2d.rpb", "module.decoder.de_trans_level3.15.na2d.rpb", "module.decoder.de_trans_level3.16.na2d.rpb", "module.decoder.de_trans_level3.17.na2d.rpb", "module.decoder.de_trans_level2.0.na2d.rpb", "module.decoder.de_trans_level2.1.na2d.rpb", "module.decoder.de_trans_level2.2.na2d.rpb", "module.decoder.de_trans_level2.3.na2d.rpb", "module.decoder.de_trans_level2.4.na2d.rpb", "module.decoder.de_trans_level2.5.na2d.rpb", "module.decoder.de_trans_level2.6.na2d.rpb", "module.decoder.de_trans_level2.7.na2d.rpb", "module.decoder.de_trans_level2.8.na2d.rpb", "module.decoder.de_trans_level2.9.na2d.rpb", "module.decoder.de_trans_level2.10.na2d.rpb", "module.decoder.de_trans_level2.11.na2d.rpb", "module.decoder.de_trans_level1.0.na2d.rpb", "module.decoder.de_trans_level1.1.na2d.rpb", "module.decoder.de_trans_level1.2.na2d.rpb", "module.decoder.de_trans_level1.3.na2d.rpb", "module.decoder.de_trans_level1.4.na2d.rpb", "module.decoder.de_trans_level1.5.na2d.rpb", "module.decoder.refinement.0.na2d.rpb", "module.decoder.refinement.1.na2d.rpb", "module.decoder.refinement.2.na2d.rpb", "module.decoder.refinement.3.na2d.rpb", "module.decoder.refinement.4.na2d.rpb", "module.decoder.refinement.5.na2d.rpb".
> > Yes indeed all the rpb's are not loading as is -- only works when the strictness is negated for the inference to work during state dict load, but I believe it will affect the performance isn't it?
> 
> ![image](https://private-user-images.githubusercontent.com/35450160/384255868-0cbf5c40-9d43-4a40-845f-747efc95e6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzAzNTYsIm5iZiI6MTczMTQ3MDA1NiwicGF0aCI6Ii8zNTQ1MDE2MC8zODQyNTU4NjgtMGNiZjVjNDAtOWQ0My00YTQwLTg0NWYtNzQ3ZWZjOTVlNmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAzNTQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMzAwOTdmZjgzNjdhZTA1NTUxNzMwODY1MTg0ODRlNGYwNGFiM2RkZWQxMTYxYjJjZDc5NmE3MGY3MTY5MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w_ejylXGjtaVvEj4CUmRVkS7IbQHW3xJTgral4y0jnk)
> 
> My natten test sample worked as expected I guess -- assuming the package installation is correct?

Please see the updated installation instructions. The issue is caused by the incompatibility of different NATTEN versions. We trained our models using the old releases.

**Comment by HanzhouLiu** [comment]
> I used pretrained DeblurDiNATL.pth downloaded from link in ReadME I tried to run script on the mac and change line 34 to use cpu > ck = torch.load(weights_path, map_location=torch.device('cpu'))
> 
> predict_GoPro_test_results.py --weight_name=DeblurDiNATL.pth --blur_path=./inputData/DeblurDiNAT Traceback (most recent call last): File "predict_GoPro_test_results.py", line 38, in model.load_state_dict(ck) File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for DataParallel: Unexpected key(s) in state_dict: "module.decoder.de_trans_level3.0.na2d.rpb", "module.decoder.de_trans_level3.1.na2d.rpb", "module.decoder.de_trans_level3.2.na2d.rpb", "module.decoder.de_trans_level3.3.na2d.rpb", "module.decoder.de_trans_level3.4.na2d.rpb", "module.decoder.de_trans_level3.5.na2d.rpb", "module.decoder.de_trans_level3.6.na2d.rpb", "module.decoder.de_trans_level3.7.na2d.rpb", "module.decoder.de_trans_level3.8.na2d.rpb", "module.decoder.de_trans_level3.9.na2d.rpb", "module.decoder.de_trans_level3.10.na2d.rpb", "module.decoder.de_trans_level3.11.na2d.rpb", "module.decoder.de_trans_level3.12.na2d.rpb", "module.decoder.de_trans_level3.13.na2d.rpb", "module.decoder.de_trans_level3.14.na2d.rpb", "module.decoder.de_trans_level3.15.na2d.rpb", "module.decoder.de_trans_level3.16.na2d.rpb", "module.decoder.de_trans_level3.17.na2d.rpb", "module.decoder.de_trans_level2.0.na2d.rpb", "module.decoder.de_trans_level2.1.na2d.rpb", "module.decoder.de_trans_level2.2.na2d.rpb", "module.decoder.de_trans_level2.3.na2d.rpb", "module.decoder.de_trans_level2.4.na2d.rpb", "module.decoder.de_trans_level2.5.na2d.rpb", "module.decoder.de_trans_level2.6.na2d.rpb", "module.decoder.de_trans_level2.7.na2d.rpb", "module.decoder.de_trans_level2.8.na2d.rpb", "module.decoder.de_trans_level2.9.na2d.rpb", "module.decoder.de_trans_level2.10.na2d.rpb", "module.decoder.de_trans_level2.11.na2d.rpb", "module.decoder.de_trans_level1.0.na2d.rpb", "module.decoder.de_trans_level1.1.na2d.rpb", "module.decoder.de_trans_level1.2.na2d.rpb", "module.decoder.de_trans_level1.3.na2d.rpb", "module.decoder.de_trans_level1.4.na2d.rpb", "module.decoder.de_trans_level1.5.na2d.rpb", "module.decoder.refinement.0.na2d.rpb", "module.decoder.refinement.1.na2d.rpb", "module.decoder.refinement.2.na2d.rpb", "module.decoder.refinement.3.na2d.rpb", "module.decoder.refinement.4.na2d.rpb", "module.decoder.refinement.5.na2d.rpb".

Please see the updated installation instructions. The issue is caused by the incompatibility of different NATTEN versions. We trained our models using the old releases.

**Comment by akshu281** [comment]
@HanzhouLiu  - Yup, this is working. Thank you!

**Comment by HanzhouLiu** [comment]
Glad to hear it! ☺️
