### ISSUE TITLE
inf_time

### ISSUE THREAD

**Issue by txy00001** [HanzhouLiu/DeblurDiNAT#7]
I am very grateful for such a good defuzzing framework for open source, I would like to ask if there is a time-consuming indicator for the inference of the model? Is there an indicator of how fast I can reason on a generic video or image? Also, is there a script for reasoning general scenarios and daily scenes?

**Comment by HanzhouLiu** [comment]
As far as I know, the inference time should not include cpu/gpu loading time. We also need to have a warm-up process before counting the inference time. I have no idea if there is such a time-assessing indicator. I read some work they deploy the model on a mobile phone and measure the latency on the phone, which is closer to daily scenes. However, we have not done such a deployment/script yet. If you would like to reproduce the inference time we have in the paper, just run the test file and the terminal log will show you the time.

**Comment by txy00001** [comment]
> 据我所知，推理时间不应该包括 cpu/gpu 加载时间。在计算推理时间之前，我们还需要有一个预热过程。我不知道是否有这样的时间评估指标。我读过一些工作，他们将模型部署在手机上，并测量手机上的延迟，这更接近日常场景。但是，我们还没有完成这样的部署/脚本。如果您想重现我们在论文中的推理时间，只需运行测试文件，终端日志就会显示时间。

Thanks for the answer, I would like to ask you if the model can be converted to onnx/trt inference? Used for deployment?

**Comment by HanzhouLiu** [comment]
> > 据我所知，推理时间不应该包括 cpu/gpu 加载时间。在计算推理时间之前，我们还需要有一个预热过程。我不知道是否有这样的时间评估指标。我读过一些工作，他们将模型部署在手机上，并测量手机上的延迟，这更接近日常场景。但是，我们还没有完成这样的部署/脚本。如果您想重现我们在论文中的推理时间，只需运行测试文件，终端日志就会显示时间。
> 
> Thanks for the answer, I would like to ask you if the model can be converted to onnx/trt inference? Used for deployment?

Sorry that I am not quite familiar with mobile deployment.
