### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'weights_path'

### ISSUE THREAD

**Issue by kawchar85** [HanzhouLiu/DeblurDiNAT#8]
While running the prediction scripts (`predict_RealBlur_R_test_results.py`, `predict_RealBlur_J_test_results.py`, `predict_HIDE_results.py`) the following error occurs:

```
AttributeError: 'Namespace' object has no attribute 'weights_path'
```

**Comment by HanzhouLiu** [comment]
Great! Thanks for your contributions.
